### ISSUE TITLE
Telegram 机器人无响应

### ISSUE THREAD

**Issue by Hell-Tractor** [framist/SAFC-bot#1]
向机器人发送指令后无任何响应

![image](https://github.com/framist/SAFC-bot/assets/32808149/c9e09c15-eba2-43dd-bcf9-c83b1b3ea5bd)

**Comment by framist** [comment]
已恢复
造成 panic 的原因或许是因为从 UTF-8 切片错误，有待观察

**Comment by framist** [comment]
fix at https://github.com/framist/SAFC-bot/commit/147ddeed89aab5ddbd00cb45dc198f95377c93a1
